### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by jameslu01** [biomathman/pycellerator#1]
Hello - 

I tried the example mentioned in the readme: 

> python pycellerator.py solve -in Gold1.model -plot

However, I got the error message from print:

> File "pycellerator.py", line 50
>     print "This is py[cellerator] version "+str(versionNumber)
>                                           ^
> SyntaxError: invalid syntax

I am running:
Python 3.6.8 :: Anaconda, Inc.

Thanks,

James

**Comment by biomathman** [comment]
Hi James, Pycellerator is implemented in Python 2.7 so your error would be expected. To work in Python 3.7 the code would have to be upgraded to Python 3. I would welcome somebody forking the code and performing the upgrade! -- BES

**Comment by jameslu01** [comment]
Thanks for the response, Bruce!
